<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="ThinkPadE550" ignored="0" name="Test" tests="12" failures="5" timestamp="29 May 2019 16:22:30 GMT" time="199.93" errors="0">
  <testcase name="isDisplayed" time="23.055" classname="eply.com.Tests.SearchAllTest"/>
  <testcase name="msgText" time="24.802" classname="eply.com.Tests.SearchAllTest">
    <failure type="java.lang.AssertionError" message="expected [The search was done] but found [The search was done.]">
      <![CDATA[java.lang.AssertionError: expected [The search was done] but found [The search was done.]
at eply.com.Tests.SearchAllTest.msgText(SearchAllTest.java:40)
... Removed 31 stack frames]]>
    </failure>
  </testcase> <!-- msgText -->
  <testcase name="isExist" time="10.266" classname="eply.com.Tests.AccountTest"/>
  <testcase name="dropDown" time="10.335" classname="eply.com.Tests.ViewMyFormsTest"/>
  <testcase name="dropDownFail" time="9.566" classname="eply.com.Tests.ViewMyFormsTest">
    <failure type="java.lang.AssertionError" message="
Shall Fail
 expected [Forms: 0] but found [Forms: 3]">
      <![CDATA[java.lang.AssertionError: 
Shall Fail
 expected [Forms: 0] but found [Forms: 3]
at eply.com.Tests.ViewMyFormsTest.dropDownFail(ViewMyFormsTest.java:39)
... Removed 30 stack frames]]>
    </failure>
  </testcase> <!-- dropDownFail -->
  <testcase name="currentPage" time="10.051" classname="eply.com.Tests.SpecificFormPageTest"/>
  <testcase name="eventSaved" time="15.684" classname="eply.com.Tests.SpecificFormPageTest"/>
  <testcase name="isErrorExist" time="14.661" classname="eply.com.Tests.SpecificFormPageTest">
    <failure type="java.lang.AssertionError" message="expected [false] but found [true]">
      <![CDATA[java.lang.AssertionError: expected [false] but found [true]
at eply.com.Tests.SpecificFormPageTest.isErrorExist(SpecificFormPageTest.java:40)
... Removed 31 stack frames]]>
    </failure>
  </testcase> <!-- isErrorExist -->
  <testcase name="isRestoreAvailable" time="1.97" classname="eply.com.Tests.ForgotPasswordTest"/>
  <testcase name="msgText" time="1.591" classname="eply.com.Tests.ForgotPasswordTest">
    <failure type="java.lang.AssertionError" message="expected [instructions on how to reset your password have been sent to the email address registered with the username provided.] but found [Instructions on how to reset your password have been sent to the email address registered with the username provided.]">
      <![CDATA[java.lang.AssertionError: expected [instructions on how to reset your password have been sent to the email address registered with the username provided.] but found [Instructions on how to reset your password have been sent to the email address registered with the username provided.]
at eply.com.Tests.ForgotPasswordTest.msgText(ForgotPasswordTest.java:31)
... Removed 31 stack frames]]>
    </failure>
  </testcase> <!-- msgText -->
  <testcase name="LoginSucceed" time="2.826" classname="eply.com.Tests.LoginTest"/>
  <testcase name="LoginFailure" time="0.8" classname="eply.com.Tests.LoginTest">
    <failure type="java.lang.AssertionError" message="expected [Sorry, either your username or password was incorrect] but found [Sorry, either your username or password was incorrect.]">
      <![CDATA[java.lang.AssertionError: expected [Sorry, either your username or password was incorrect] but found [Sorry, either your username or password was incorrect.]
at eply.com.Tests.LoginTest.LoginFailure(LoginTest.java:18)
... Removed 31 stack frames]]>
    </failure>
  </testcase> <!-- LoginFailure -->
</testsuite> <!-- Test -->
